### ISSUE TITLE
pathDefinition is undefined when pathDefinition.type is checked

### ISSUE THREAD

**Issue by hoffmanr-cshs** [sync-for-science/data-census#1]
I encountered the following error when running the builder scripts:

```
...
    ✔ v3-codesystems.json
    ✖ valuesets.json
      → Cannot read properties of undefined (reading 'type')
    Generate Output File
[project_dir]/data-census/builder/src/summarizer.js:39
		if (pathSegments[i-1] === "contained" && pathDefinition.type[0] === pathDefinition.type[0].toUpperCase())
		                                                        ^

TypeError: Cannot read properties of undefined (reading 'type')
    at [project_dir]/data-census/builder/src/summarizer.js:39:59
    at Array.forEach (<anonymous>)
    at pathToFhirType ([project_dir]/data-census/builder/src/summarizer.js:33:15)
    at summarizeElement ([project_dir]/data-census/builder/src/summarizer.js:67:24)
    at [project_dir]/data-census/builder/src/summarizer.js:218:4
    at [project_dir]/data-census/builder/node_modules/lodash/lodash.js:3585:27
    at [project_dir]/data-census/builder/node_modules/lodash/lodash.js:4967:15
    at baseForOwn ([project_dir]/data-census/builder/node_modules/lodash/lodash.js:3032:24)
    at [project_dir]/data-census/builder/node_modules/lodash/lodash.js:4936:18
    at baseMap ([project_dir]/data-census/builder/node_modules/lodash/lodash.js:3584:7) {
  context: [Object: null prototype] {}
}
...
```

I was able to resolve this by moving the "shortcut" referenced on line 38 of summarizer.js after the check for an undefined pathDefinition that is currently on line 43. Before submitting a PR with that fix though, I wanted to check and make sure that the change wouldn't defeat the purpose of including that check for contained resources in the first place.

Thanks!

**Comment by gotdan** [comment]
Hmm, something seems off since it looks like the builder is trying to parse the FHIR definition files as resources. What does your command look like - is it possible that the -p and -r flags are reversed?

**Comment by hoffmanr-cshs** [comment]
Whoops, sorry about that! In fact it looks like I left the -p flag out altogether, and it was trying to process the definitions as a second directory of resources. Thanks!
